# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               忘了鬼島忘了我
tagline:             '人生長恨 水長東 stuff about mathematics and physics'
description:         '一些數學物理和生活隨筆還有廢文'
url:                 http://lanyon.getpoole.com
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
